SlackToken: ""
SlackBotToken: ""
PidFilePath: "/home/username"
ChannelToMonitor: ""
ChannelToMessage: ""
SlackUser: ""
SlackWebHook: "https://hooks.slack.com/services/blah/blah"
SlackMessageText: "Check out this message"
TriggerWords: ["@here", "test"]
