SlackToken: "123abc"
BaseURL: "https://slack.com/api/"
ChannelToMonitor: ""
ChannelToMessage: ""
TriggerWords:
  [
    "@here",
    "leftover",
    "pizza",
    "bagel",
    "sandwich",
    "cake",
    "ice cream",
    "dessert",
  ]
